# -*- coding: utf-8 -*-
{
    'name': 'School Management',
    'summary': 'School Management',
    'installable': True,
    'auto_install': False,
    'sequence': 0,
    'version': '19.0.1.0.0',
    'category': 'School Management',
    'application': True,
    'depends': ['base','mail','sale','base_automation'],
    'data': [
        'security/ir.model.access.csv',
        'security/user_groups.xml',
        # 'security/ir_rules.xml',
        'data/sequence_data.xml',
        'data/department_data.xml',
        'data/class_data.xml',
        'data/subject_data.xml',
        'data/email_template_data.xml',
        'data/automation_action.xml',
        'data/ir_cron_data.xml',
        'views/school_registration_views.xml',
        'views/manage_department_views.xml',
        'views/manage_subject_views.xml',
        'views/manage_class_views.xml',
        'views/manage_academic_year_views.xml',
        'views/registered_student_views.xml',
        'views/student_club_views.xml',
        'views/club_event_views.xml',
        'views/sale_order_inherited_views.xml',
        'views/partner_extend_inherit_view.xml',
        'views/employee_teacher_views.xml',
        'views/employee_office_staff_views.xml',
        'views/school_leave_views.xml',
        'views/student_exam_views.xml',
        'views/school_management_menus.xml'
    ]
}
